8 feat airflow implemantation (#30)
* feat: Airflow Implementation

* fix: poke interval set to 2 minutes

* docs: Remove the PostgreSQL volume before containers initialization

* chore: Removing old sql script

* fix: Changing CD tasks order

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -39,6 +39,62 @@ jobs:
     needs: validate
     runs-on: ubuntu-latest
     steps:
+    - name: Code sync
+      uses: appleboy/ssh-action@v1.0.0
+      with:
+        host: ${{ secrets.VM_HOST }}
+        username: ${{ secrets.VM_USER }}
+        key: ${{ secrets.SSH_PRIVATE_KEY }}
+        script: |
+          set -e 
+
+          PROJECT_DIR="${{ secrets.VM_PROJECT_DIR }}"
+        
+          if [ ! -d "$PROJECT_DIR" ]; then
+            echo "ERROR: Project directory not found: Please check the VM_PROJECT_DIR secret."
+            exit 1
+          fi
+          
+          cd "$PROJECT_DIR"
+          
+          git pull origin main
+          
+          if [ ! -f .env ]; then
+            echo "There is no .env file. Please create it from .env.example."
+            exit 1
+          fi
+
+    - name: System setup (initial deployment)
+      uses: appleboy/ssh-action@v1.0.0
+      with:
+        host: ${{ secrets.VM_HOST }}
+        username: ${{ secrets.VM_USER }}
+        key: ${{ secrets.SSH_PRIVATE_KEY }}
+        script: |
+          set -e 
+
+          PROJECT_DIR="${{ secrets.VM_PROJECT_DIR }}"
+        
+          if [ ! -d "$PROJECT_DIR" ]; then
+            echo "ERROR: Project directory not found: Please check the VM_PROJECT_DIR secret."
+            exit 1
+          fi
+          
+          cd "$PROJECT_DIR"
+
+          if ! command -v docker &> /dev/null; then
+            echo "Docker is not installed. Installing Docker..."
+            if [ -f scripts/initial_deployment.sh ]; then
+              sudo chmod +x scripts/initial_deployment.sh
+              ./scripts/initial_deployment.sh
+            else
+              echo "Initial deployment script not found."
+              exit 1
+            fi
+          else
+            echo "Docker detected. Skipping Docker installation."
+          fi
+
     - name: Check lockfile on VM (legacy)
       uses: appleboy/ssh-action@v1.0.0
       with:
@@ -86,63 +142,6 @@ jobs:
           else
             echo "Running dags check script not found."
             exit 1
-          fi
-
-
-    - name: Code sync
-      uses: appleboy/ssh-action@v1.0.0
-      with:
-        host: ${{ secrets.VM_HOST }}
-        username: ${{ secrets.VM_USER }}
-        key: ${{ secrets.SSH_PRIVATE_KEY }}
-        script: |
-          set -e 
-
-          PROJECT_DIR="${{ secrets.VM_PROJECT_DIR }}"
-        
-          if [ ! -d "$PROJECT_DIR" ]; then
-            echo "ERROR: Project directory not found: Please check the VM_PROJECT_DIR secret."
-            exit 1
-          fi
-          
-          cd "$PROJECT_DIR"
-          
-          git pull origin main
-          
-          if [ ! -f .env ]; then
-            echo "There is no .env file. Please create it from .env.example."
-            exit 1
-          fi
-          
-    - name: System setup (initial deployment)
-      uses: appleboy/ssh-action@v1.0.0
-      with:
-        host: ${{ secrets.VM_HOST }}
-        username: ${{ secrets.VM_USER }}
-        key: ${{ secrets.SSH_PRIVATE_KEY }}
-        script: |
-          set -e 
-
-          PROJECT_DIR="${{ secrets.VM_PROJECT_DIR }}"
-        
-          if [ ! -d "$PROJECT_DIR" ]; then
-            echo "ERROR: Project directory not found: Please check the VM_PROJECT_DIR secret."
-            exit 1
-          fi
-          
-          cd "$PROJECT_DIR"
-
-          if ! command -v docker &> /dev/null; then
-            echo "Docker is not installed. Installing Docker..."
-            if [ -f scripts/initial_deployment.sh ]; then
-              sudo chmod +x scripts/initial_deployment.sh
-              ./scripts/initial_deployment.sh
-            else
-              echo "Initial deployment script not found."
-              exit 1
-            fi
-          else
-            echo "Docker detected. Skipping Docker installation."
           fi
     
     - name: Containers deployment
